### ISSUE TITLE
Website copy: Google spreadsheet

### ISSUE THREAD

**Issue by xMartin** [unhosted/opentabs#6]
Why does it have to be a "Google" spreadsheet? I wouldn't use a product name, here.

**Comment by michielbdejong** [comment]
what i meant there is the fact we used GoogleDocs for online collaboration, combined with the spreadsheet functionality to automatically update the latest balances. is there a generic brand-neutral way to say GoogleDocs? an "online collaborative spreadsheet"? i think that is really less clear

**Comment by raucao** [comment]
Why not use an Etherpad?

**Comment by michielbdejong** [comment]
yes, that would be another example.

```
You can do this in several ways, for instance:

  on a piece of paper,
  in a text note on your phone
  with a GoogleDocs Spreadsheet
  in an email thread, or
  using a specialized app like xMartin's GroupTabs.
```

you could also use marks on twigs or just use your memory or a github repo. should i really add more than 5 examples here?

why does everybody suddenly care so much about the placeholder website of a dormant project. if you guys really care about working on opentabs and there is enthusiasm for it, then maybe let's revive the project between all of us, and continue developing GroupTabs?

**Comment by jancborchardt** [comment]
I think what @xMartin means is simply that we shouldn’t endorse or namedrop Google Docs specifically because that’s not the only collaborative spreadsheet there is (see [EtherCalc](http://ethercalc.net/) for instance). So I changed it to »collaborative spreadsheet«. No big discussion necessary.

**Comment by melvincarvalho** [comment]
On 18 February 2013 10:51, Jan-Christoph Borchardt <notifications@github.com

> wrote:
> 
> I think what @xMartin https://github.com/xMartin means is simply that
> we shouldn’t endorse or namedrop Google Docs specifically because that’s
> not the only collaborative spreadsheet there is (see EtherCalchttp://ethercalc.net/for instance). So I changed it to »collaborative spreadsheet«. No big
> discussion necessary.
> 
> Yes it's funny you mention that.  Timbl was asked about facebook at campus
> party.

And he said, 'I cant comment on individual companies, but can talk about
social networks'.  Later on in the same talk he said, 'If you GOOGLE ...'
-- ie using google as a verb.  It's easy to forget!

Maybe just 'shared spreadsheet' fits here ...
